apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  # https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customizing-jenkins/
  1-system-message.yaml: |
    jenkins:
      systemMessage: "Configuration as Code integration works!!!"
  2-job-dsl.yaml: |
    jobs:
      - script: >-
          multibranchPipelineJob('Halogen Chess') {
              branchSources {
                  git {
                      id = 'Halogen Chess'
                      remote('https://github.com/peterbecich/halogen-chess.git')
                   }
              }
          }
  3-kubernetes-plugin.yaml: |
    jenkins:
      clouds:
        - kubernetes:
            name: "advanced-k8s-config"
            # serverUrl: "https://advanced-k8s-config:443"
            # serverCertificate: "serverCertificate"
            skipTlsVerify: true
            # credentialsId: "advanced-k8s-credentials"
            namespace: "default"
            # jenkinsUrl: "http://jenkins/"
            # jenkinsTunnel: "jenkinsTunnel"
            containerCapStr: 10
            maxRequestsPerHostStr: 64
            retentionTimeout: 5
            connectTimeout: 10
            readTimeout: 20

            templates:
              - name: "test"
                serviceAccount: "serviceAccount"
                instanceCap: 20
                idleMinutes: 0
                # label: "label"
                # Enable whether the POD Yaml is displayed in each build log or not, `true` by default.
                showRawYaml: true

                # volumes:
                #   - hostPathVolume:
                #       mountPath: "mountPath"
                #       hostPath: "hostPath"

                containers:
                  - name: "alpine"
                    image: "3.16.3"
                    privileged: true
                    alwaysPullImage: true
                    command: "command"
                    args: "args"
                    workingDir: "workingDir"
                    ttyEnabled: true
                    # resourceRequestCpu: "resourceRequestCpu"
                    # resourceRequestMemory: "resourceRequestMemory"
                    # resourceLimitCpu: "resourceLimitCpu"
                    # resourceLimitMemory: "resourceLimitMemory"
                # imagePullSecrets:
                #   - name: "imagePullSecrets"

                # envVars:
                #   - envVar:
                #       key: "FOO"
                #       value: "BAR"

              - name: "k8s-agent"
                namespace: "default"
                label: "linux-x86_64"
                nodeUsageMode: EXCLUSIVE
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:4.10-3"
                    alwaysPullImage: true
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
                volumes:
                  - emptyDirVolume:
                      memory: false
                      mountPath: "/tmp"
                  # Mount the content of the ConfigMap `configmap-name` with the data `config`.
                  # - configMapVolume:
                  #     configMapName: configmap-name
                  #     mountPath: /home/jenkins/.aws/config
                  #     subPath: config
                idleMinutes: "1"
                activeDeadlineSeconds: "120"
                slaveConnectTimeout: "1000"
