apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: default
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
