# https://github.com/marketplace/actions/ormolu-action
name: Ormolu

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: '**'

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v7
  build:
    runs-on: ubuntu-latest
    needs: ormolu

    steps:
    - uses: actions/checkout@v2
